permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: Archaic Records
  description: A small record label that gives up and coming talented musicians a platform to promote their art.
  font_url: "https://use.typekit.net/slb4bkf.css"
  colors:
    background: "--color-primary-light"
    accent: "--color-primary-dark"
    patterns:
      brand.logos: "--color-primary"
  rationales:
    typefaces.primary:
      The primary typeface - Century Gothic was chosen because of it's legibility and stylistic values. An easy to read sans serif font for small headers and body copy.
    typefaces.secondary:
      The secondary typeface - Urbane Rounded is used for main headers, it has playful graffiti like features, and speaks to the lively, high-spirited while serious proffesional traits valued at Archaic Records.
    colors.primary:
      The primary colours were chosen because of their simplicity and visibility, Archaic records wants to be represented as an indie/alternative label. Dark colurs show that we take all clients very seriously, and they personify the struggle many musicians may face.
    colors.secondary:
      The secondary colour is a plain white, chosen to contrast the dark primary colours, and in case there is any text that needs to be placed on a dark background. White also compliments the simplicity Archaic's brand wishes to acheive.
  layouts:
    default: |
      The default layout should be used for almost every page, it includes the websites primary header and footer.
