permalink: pretty
theme: jekyll_patternbot

patternbot:
  title: Archaic Records
  description: A small record label that gives up and coming talented musicians a platform to promote their art.
  font_url: "https://use.typekit.net/slb4bkf.css"
