title: "Forms"
description: |
  Form page includes all the required form fields a user must complete before registration.

patterns:
  receivenews:
    title: "Receive News"
    description: |
        User will check box if they wish to receive emails with news about Archaic Records.

  email:
    title: "Email"
    description: |
      Enter valid email address in to required field, user must also verify their email address.

  terms:
    title: terms
    description: |
      Click check box when registering in order to agree to Archaic Records terms and conditions
