title: "Receive News"
description: |
  User is to click check box when registering should they wish to reveive news and updates from Archaic Records.
title: "Email"
description: |
  Enter valid email address in to required field, user must also verify their email address.
title: "Terms"
description: |
  Click check box when registering in order to agree to Archaic Records terms and conditions
