title: "Cards"
description: |
  Cards are used to advertise merchandise, they will appear frequently throughout the site with different images inside them.

patterns:
  product:
    title: "Hoodie"
    description: |
      Cards are used to advertise merchandise, they will appear frequently throughout the site with different images inside them.
    width: "14em"
    fields:
      - name: data2
        type: object
        data:
          source: "site.products[0]"
          type: Product
  featured:
    title: "Featured New Music"
    description: |
      This card is used only on the home page to advertise new releases. This will appear once throughout the site, but will update as new music is released, with different images placed inside to promote the merchandise.
    fields:
      - name: data2
        type: object
        data:
          source: "site.products[0]"
          type: Product
