title: "Banner"
description: |
  Navigation is the banner running along the top of the website.

patterns:
  banner:
    title: "Banner"
    description: |
      Banner is the navigation running along the top of all pages.
